### ISSUE TITLE
配置文件增加当掉落物数量达到阈值时启动自动清理掉落物

### ISSUE THREAD

**Issue by yufengya0420** [Tsubasa6848/DespawnLags#3]
配置文件增加当掉落物数量达到阈值时启动自动清理掉落物

**Comment by Tsubasa6848** [comment]
本插件是修改掉落物存在时长，并不会清理掉落物。
因此请描述达到阈值启动自动清理是什么意思？
本插件不会启用任何自动清理，仅修改掉落物存在时长。

**Comment by Tsubasa6848** [comment]
如果我理解错了你的意思，请描述清楚你的具体意思。
我暂时先把Issue关了，有需求请重新打开这个Issue。

**Comment by yufengya0420** [comment]
> 如果我理解错了你的意思，请描述清楚你的具体意思。 我暂时先把Issue关了，有需求请重新打开这个Issue。

就是想cleaner一样，掉落物数量达到一定值的时候，进行一次掉落物清理，这里指的清理是指用你的插件清理掉落物的原理（刷新）从而使掉落物消失

**Comment by Tsubasa6848** [comment]
这个插件只修改掉落物存在时间。Cleaner有掉落物清理功能，你可以考虑使用Cleaner清理掉落物
