### ISSUE TITLE
掉落物清理的时候好像会清理非生物实体

### ISSUE THREAD

**Issue by yufengya0420** [Tsubasa6848/DespawnLags#4]
掉落物清理的时候好像会清理非生物实体，我服有人说他的三叉戟好几次消失了，（丢出去的三叉戟做搅拌机）

**Comment by Tsubasa6848** [comment]
BDS-1.19.73 无法复现。
请检查是否为其他原因导致消失？（三叉戟卡进方块等）

如果依旧认定为本插件问题，请提供具体的复现方案。

**Comment by Tsubasa6848** [comment]
经核实，本插件不会导致三叉戟消失。
三叉戟消失与本插件无关，请排查其他原因。

如有问题请重新打开Issue。
