### ISSUE TITLE
Update to BDS1.19.81 LL2.13.0

### ISSUE THREAD

**Issue by zevlaoxie2010** [Tsubasa6848/DespawnLags#5]
It cannot be used in the new version
![2](https://user-images.githubusercontent.com/95100738/236663231-2c92a198-42c6-4aca-9853-ea261bd81c3d.png)
The program cannot continue

**Comment by Tsubasa6848** [comment]
commit [676e4f8](https://github.com/Tsubasa6848/DespawnLags/commit/676e4f84b09a52212cb0833ed69450407e231e45)
