### ISSUE TITLE
1.20.11适配问题

### ISSUE THREAD

**Issue by lthuas** [Tsubasa6848/DespawnLags#6]
似乎不适配最新的1.20.11啦，10用的时候没有报错。
![image](https://github.com/Tsubasa6848/DespawnLags/assets/99377251/1bb08777-9d6a-4324-9268-813d02a2446e)

**Comment by Tsubasa6848** [comment]
这并不是这个插件报错

**Comment by lthuas** [comment]
> 这并不是这个插件报错

非常抱歉作者，我拿错图了，是这个
![屏幕截图 2023-07-16 221349](https://github.com/Tsubasa6848/DespawnLags/assets/99377251/2eef0602-30cc-45e9-a2bf-95a5f63c2ac6)
